name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
#    runs-on: MyLaptop

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      BUILDKIT_PROGRESS: plain    

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: manimaran7499/app:latest


  deploy:
    runs-on: MyLaptop 
    needs: build

    steps:
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET }}

    - name: Pull Docker image
      run: docker pull manimaran7499/app:latest

    - name: Run Docker container
      run: |
        docker run -d --name my-app-container -p 8080:8080 manimaran7499/app:latest
        
